### ISSUE TITLE
Risk of orphaned AMI if no volume attached

### ISSUE THREAD

**Issue by apio-sys** [arnaud-coral/AWS-Delete-unused-EBS-snapshots#1]
Good work Arnaud, looks great! Was able to delete quite a few snapshots with it using dry-run first. But what about a snapshot belonging to an AMI that has no EC2 booted and thus no volume attached? Ie. a template AMI for which you don't keep an EC2 running (or even off). WHen launching, the AMI would still need it's snapshot(s) to boot a new machine. But they would have been deleted by the script since not linked to any volume... 😕. Maybe an extra check to implement?

J.

**Comment by arnaud-coral** [comment]
Hi J,

Hope you're good? ;)

Thank you for your comment.
The snapshots list is filtered to retrieve only the ones not linked to any AMI, not volumes. The comments and the readme weren't up-to-date.

By the way, this showed me another issue: using this script would delete any snapshot linked to an AMI not yet created. So, I modified filters to include the "pending" state in addition to "available".

A.
